import { Ionicons } from "@/components/ionicons";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { EmptyState } from "@/components/empty-state";
import { useColors } from "@/hooks/use-colors";
import { Radii, Spacing, Typography } from "@/lib/_core/theme";
import { getSafeErrorMessage } from "@/lib/error-message";
import { useTranslation } from "@/lib/i18n-provider";
import { listNotifications, markNotificationRead } from "@/lib/backend/notifications";
import { useFirebaseAuth } from "@/hooks/use-firebase-auth";
import type { NotificationItem } from "@/types/domain";
export default function NotificationsScreen() {
  const colors = useColors("light"); const { t } = useTranslation(); const { session } = useFirebaseAuth();
  const [items, setItems] = useState<NotificationItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const userId = session?.user.id;
  const load = useCallback(async () => { if (!userId) return; setLoading(true); try { setError(null); setItems(await listNotifications(userId)); } catch (cause) { setError(getSafeErrorMessage(cause, "network")); } finally { setLoading(false); } }, [userId]);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const read = async (item: NotificationItem) => { if (item.read) return; setItems((current) => current.map((entry) => entry.id === item.id ? { ...entry, read: true } : entry)); try { await markNotificationRead(item.id); } catch { await load(); } };
  return <View style={[styles.root, { backgroundColor: colors.background }]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} tintColor={colors.primary} />}><Text style={[styles.title, { color: colors.foreground }]}>{t("notifications.title")}</Text><Text style={[styles.subtitle, { color: colors.muted }]}>{t("notifications.emptyBody")}</Text>{error ? <Text style={[styles.error, { color: colors.error }]}>{error}</Text> : null}{loading && items.length === 0 ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : items.length === 0 ? <EmptyState title={t("notifications.emptyTitle")} body={t("notifications.emptyBody")} icon="notifications-outline" /> : items.map((item) => <View key={item.id} onTouchEnd={() => void read(item)} style={[styles.item, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.icon, { backgroundColor: item.read ? colors.background : colors.primarySoft }]}><Ionicons name={item.kind === "PAYMENT" ? "receipt-outline" : item.kind === "POST" ? "document-text-outline" : "megaphone-outline"} size={20} color={item.read ? colors.muted : colors.primaryDark} /></View><View style={styles.copy}><View style={styles.itemHeader}><Text style={[styles.itemTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.time, { color: colors.muted }]}>{item.createdAtLabel}</Text></View><Text style={[styles.body, { color: colors.muted }]}>{item.body}</Text></View>{!item.read ? <View style={[styles.dot, { backgroundColor: colors.primary }]} /> : null}</View>)}</ScrollView></View>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, content: { paddingHorizontal: Spacing.page, paddingTop: Spacing.xl, paddingBottom: 32, maxWidth: 720, width: "100%", alignSelf: "center" }, title: { ...Typography.title }, subtitle: { ...Typography.body, marginTop: 4, marginBottom: Spacing.xl }, error: { ...Typography.caption, marginBottom: Spacing.md }, loader: { marginVertical: Spacing.xxl }, item: { flexDirection: "row", alignItems: "flex-start", gap: Spacing.md, borderWidth: 1, borderRadius: Radii.md, padding: Spacing.lg, marginBottom: Spacing.md }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, itemHeader: { flexDirection: "row", justifyContent: "space-between", gap: Spacing.sm }, itemTitle: { ...Typography.body, fontWeight: "700", flex: 1 }, time: { ...Typography.caption }, body: { ...Typography.caption, lineHeight: 18, marginTop: 4 }, dot: { width: 7, height: 7, borderRadius: 4, marginTop: 6 } });
